services:
  web:
    build: .
    ports:
      - "8001:8001"
    command: python manage.py runserver 0.0.0.0:8001
    env_file:
        - .env
    volumes:
      - .:/django_project
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: